
INFLUX_HOST = "https://alpinemeteo.com:8086"
INFLUX_ORG = "snow"
INFLUX_STATION_BUCKET = "stationdb"
INFLUX_STATION_API_KEY = "<STATION-APIKEY>"
INFLUX_METADATA_BUCKET = "stationmetadb"
INFLUX_METADATA_API_KEY = "<METADATA-APIKEY>"
